import { jsx as _jsx } from "react/jsx-runtime";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children, }) {
    return (_jsx("html", { lang: "en", className: `${geistSans.variable} ${geistMono.variable} h-full antialiased`, children: _jsx("body", { className: "min-h-full flex flex-col", children: children }) }));
}
//# sourceMappingURL=layout.js.map