import * as Icons from "@/src";

export default function Home() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
      {allIcons.map((item, index) => {
        const IconComponent = Icons[item.name];
        const IconType = item.isRaster ? "Raster" : "Vector";
        if (IconComponent)
          if (IconType === "Raster") {
            return (
              <div className="flex gap-7">
                <h1 className="text-7xl">{index + 1}</h1>
                <IconComponent
                  className="outline-10"
                  color="red"
                  key={index}
                  size={100}
                />
              </div>
            );
          } else {
            return (
              <div className="flex gap-7">
                <h1 className="text-7xl">{index + 1}</h1>
                <IconComponent
                  className="outline-1"
                  color="blue"
                  key={index}
                  size={200}
                />
              </div>
            );
          }
      })}
    </div>
  );
}

const allIcons = [
  {
    name: "Aastu",
    filename: "Aastu.tsx",
    type: "Raster Image",
    sizeBytes: 82106,
    sizeFormatted: "80.2 KB",
    isRaster: false,
  },
  {
    name: "Aau",
    filename: "Aau.tsx",
    type: "Raster Image",
    sizeBytes: 104249,
    sizeFormatted: "101.8 KB",
    isRaster: true,
  },
  {
    name: "AbayBank",
    filename: "AbayBank.tsx",
    type: "Pure Vector",
    sizeBytes: 2410,
    sizeFormatted: "2.4 KB",
    isRaster: false,
  },
  {
    name: "AbayBankBlueBg",
    filename: "AbayBankBlueBg.tsx",
    type: "Pure Vector",
    sizeBytes: 2497,
    sizeFormatted: "2.4 KB",
    isRaster: false,
  },
  {
    name: "AbayBankTitle",
    filename: "AbayBankTitle.tsx",
    type: "Pure Vector",
    sizeBytes: 5721,
    sizeFormatted: "5.6 KB",
    isRaster: false,
  },
  {
    name: "AbayBankTitleBlueBg",
    filename: "AbayBankTitleBlueBg.tsx",
    type: "Pure Vector",
    sizeBytes: 5808,
    sizeFormatted: "5.7 KB",
    isRaster: false,
  },
  {
    name: "AbayBankVerticalTitleBlueBg",
    filename: "AbayBankVerticalTitleBlueBg.tsx",
    type: "Pure Vector",
    sizeBytes: 8459,
    sizeFormatted: "8.3 KB",
    isRaster: false,
  },
  {
    name: "AfricanUnion",
    filename: "AfricanUnion.tsx",
    type: "Raster Image",
    sizeBytes: 58144,
    sizeFormatted: "56.8 KB",
    isRaster: true,
  },
  {
    name: "AirForce",
    filename: "AirForce.tsx",
    type: "Raster Image",
    sizeBytes: 52511,
    sizeFormatted: "51.3 KB",
    isRaster: false,
  },
  {
    name: "AmharaBank",
    filename: "AmharaBank.tsx",
    type: "Pure Vector",
    sizeBytes: 6166,
    sizeFormatted: "6.0 KB",
    isRaster: false,
  },
  {
    name: "Amole",
    filename: "Amole.tsx",
    type: "Raster Image",
    sizeBytes: 588349,
    sizeFormatted: "574.6 KB",
    isRaster: false,
  },
  {
    name: "Ata",
    filename: "Ata.tsx",
    type: "Raster Image",
    sizeBytes: 62090,
    sizeFormatted: "60.6 KB",
    isRaster: true,
  },
  {
    name: "AwashBank",
    filename: "AwashBank.tsx",
    type: "Pure Vector",
    sizeBytes: 11758,
    sizeFormatted: "11.5 KB",
    isRaster: false,
  },
  {
    name: "AwashBankNoText",
    filename: "AwashBankNoText.tsx",
    type: "Pure Vector",
    sizeBytes: 3635,
    sizeFormatted: "3.5 KB",
    isRaster: false,
  },
  {
    name: "AyatRealEstate",
    filename: "AyatRealEstate.tsx",
    type: "Raster Image",
    sizeBytes: 46756,
    sizeFormatted: "45.7 KB",
    isRaster: true,
  },
  {
    name: "BandiraAddis",
    filename: "BandiraAddis.tsx",
    type: "Pure Vector",
    sizeBytes: 20313,
    sizeFormatted: "19.8 KB",
    isRaster: false,
  },
  {
    name: "Bdu",
    filename: "Bdu.tsx",
    type: "Raster Image",
    sizeBytes: 777108,
    sizeFormatted: "758.9 KB",
    isRaster: true,
  },
  {
    name: "BlueMoon",
    filename: "BlueMoon.tsx",
    type: "Raster Image",
    sizeBytes: 127639,
    sizeFormatted: "124.6 KB",
    isRaster: true,
  },
  {
    name: "Boa",
    filename: "Boa.tsx",
    type: "Raster Image",
    sizeBytes: 60380,
    sizeFormatted: "59.0 KB",
    isRaster: true,
  },
  {
    name: "Cbe",
    filename: "Cbe.tsx",
    type: "Raster Image",
    sizeBytes: 331237,
    sizeFormatted: "323.5 KB",
    isRaster: true,
  },
  {
    name: "CbeBirr",
    filename: "CbeBirr.tsx",
    type: "Pure Vector",
    sizeBytes: 14023,
    sizeFormatted: "13.7 KB",
    isRaster: false,
  },
  {
    name: "CbeBirrLight",
    filename: "CbeBirrLight.tsx",
    type: "Pure Vector",
    sizeBytes: 10923,
    sizeFormatted: "10.7 KB",
    isRaster: false,
  },
  {
    name: "Cellutech",
    filename: "Cellutech.tsx",
    type: "Pure Vector",
    sizeBytes: 159563,
    sizeFormatted: "155.8 KB",
    isRaster: true,
  },
  {
    name: "Chapa",
    filename: "Chapa.tsx",
    type: "Pure Vector",
    sizeBytes: 5465,
    sizeFormatted: "5.3 KB",
    isRaster: false,
  },
  {
    name: "ChapaGradient",
    filename: "ChapaGradient.tsx",
    type: "Pure Vector",
    sizeBytes: 15846,
    sizeFormatted: "15.5 KB",
    isRaster: false,
  },
  {
    name: "ChapaNoText",
    filename: "ChapaNoText.tsx",
    type: "Pure Vector",
    sizeBytes: 7969,
    sizeFormatted: "7.8 KB",
    isRaster: false,
  },
  {
    name: "CoopBank",
    filename: "CoopBank.tsx",
    type: "Raster Image",
    sizeBytes: 65431,
    sizeFormatted: "63.9 KB",
    isRaster: true,
  },
  {
    name: "Dangote",
    filename: "Dangote.tsx",
    type: "Pure Vector",
    sizeBytes: 8078,
    sizeFormatted: "7.9 KB",
    isRaster: false,
  },
  {
    name: "DashenBank",
    filename: "DashenBank.tsx",
    type: "Pure Vector",
    sizeBytes: 7795,
    sizeFormatted: "7.6 KB",
    isRaster: false,
  },
  {
    name: "DefenseForce",
    filename: "DefenseForce.tsx",
    type: "Raster Image",
    sizeBytes: 149817,
    sizeFormatted: "146.3 KB",
    isRaster: false,
  },
  {
    name: "EthiopianAirlines",
    filename: "EthiopianAirlines.tsx",
    type: "Raster Image",
    sizeBytes: 57121,
    sizeFormatted: "55.8 KB",
    isRaster: true,
  },
  {
    name: "EthiopianAirlinesSymbol",
    filename: "EthiopianAirlinesSymbol.tsx",
    type: "Pure Vector",
    sizeBytes: 6041,
    sizeFormatted: "5.9 KB",
    isRaster: false,
  },
  {
    name: "EthioTelecom",
    filename: "EthioTelecom.tsx",
    type: "Raster Image",
    sizeBytes: 130431,
    sizeFormatted: "127.4 KB",
    isRaster: true,
  },
  {
    name: "FlintstoneHomes",
    filename: "FlintstoneHomes.tsx",
    type: "Raster Image",
    sizeBytes: 190327,
    sizeFormatted: "185.9 KB",
    isRaster: true,
  },
  {
    name: "Gasha",
    filename: "Gasha.tsx",
    type: "Raster Image",
    sizeBytes: 8257,
    sizeFormatted: "8.1 KB",
    isRaster: false,
  },
  {
    name: "GiftRealEstate",
    filename: "GiftRealEstate.tsx",
    type: "Raster Image",
    sizeBytes: 44244,
    sizeFormatted: "43.2 KB",
    isRaster: true,
  },
  {
    name: "HabeshaBeer",
    filename: "HabeshaBeer.tsx",
    type: "Raster Image",
    sizeBytes: 1377317,
    sizeFormatted: "1345.0 KB",
    isRaster: false,
  },
  {
    name: "HibretBank",
    filename: "HibretBank.tsx",
    type: "Pure Vector",
    sizeBytes: 8929,
    sizeFormatted: "8.7 KB",
    isRaster: false,
  },
  {
    name: "HibretBankNoText",
    filename: "HibretBankNoText.tsx",
    type: "Pure Vector",
    sizeBytes: 3200,
    sizeFormatted: "3.1 KB",
    isRaster: false,
  },
  {
    name: "Hilton",
    filename: "Hilton.tsx",
    type: "Raster Image",
    sizeBytes: 46449,
    sizeFormatted: "45.4 KB",
    isRaster: true,
  },
  {
    name: "HyattRegency",
    filename: "HyattRegency.tsx",
    type: "Raster Image",
    sizeBytes: 80130,
    sizeFormatted: "78.3 KB",
    isRaster: true,
  },
  {
    name: "Iceaddis",
    filename: "Iceaddis.tsx",
    type: "Pure Vector",
    sizeBytes: 8950,
    sizeFormatted: "8.7 KB",
    isRaster: false,
  },
  {
    name: "Innohub",
    filename: "Innohub.tsx",
    type: "Raster Image",
    sizeBytes: 12903,
    sizeFormatted: "12.6 KB",
    isRaster: true,
  },
  {
    name: "Ju",
    filename: "Ju.tsx",
    type: "Raster Image",
    sizeBytes: 96164,
    sizeFormatted: "93.9 KB",
    isRaster: true,
  },
  {
    name: "Kacha",
    filename: "Kacha.tsx",
    type: "Pure Vector",
    sizeBytes: 9640,
    sizeFormatted: "9.4 KB",
    isRaster: false,
  },
  {
    name: "KuriftuResort",
    filename: "KuriftuResort.tsx",
    type: "Pure Vector",
    sizeBytes: 92635,
    sizeFormatted: "90.5 KB",
    isRaster: false,
  },
  {
    name: "LegacyRealEstate",
    filename: "LegacyRealEstate.tsx",
    type: "Raster Image",
    sizeBytes: 20167,
    sizeFormatted: "19.7 KB",
    isRaster: true,
  },
  {
    name: "LolineMag",
    filename: "LolineMag.tsx",
    type: "Pure Vector",
    sizeBytes: 3545,
    sizeFormatted: "3.5 KB",
    isRaster: true,
  },
  {
    name: "Marriott",
    filename: "Marriott.tsx",
    type: "Pure Vector",
    sizeBytes: 6276,
    sizeFormatted: "6.1 KB",
    isRaster: false,
  },
  {
    name: "Mice",
    filename: "Mice.tsx",
    type: "Raster Image",
    sizeBytes: 53685,
    sizeFormatted: "52.4 KB",
    isRaster: true,
  },
  {
    name: "Moenco",
    filename: "Moenco.tsx",
    type: "Raster Image",
    sizeBytes: 30076,
    sizeFormatted: "29.4 KB",
    isRaster: true,
  },
  {
    name: "Moh",
    filename: "Moh.tsx",
    type: "Raster Image",
    sizeBytes: 311785,
    sizeFormatted: "304.5 KB",
    isRaster: true,
  },
  {
    name: "Mop",
    filename: "Mop.tsx",
    type: "Raster Image",
    sizeBytes: 125483,
    sizeFormatted: "122.5 KB",
    isRaster: true,
  },
  {
    name: "Mot",
    filename: "Mot.tsx",
    type: "Raster Image",
    sizeBytes: 70155,
    sizeFormatted: "68.5 KB",
    isRaster: true,
  },
  {
    name: "Mpesa",
    filename: "Mpesa.tsx",
    type: "Pure Vector",
    sizeBytes: 3153,
    sizeFormatted: "3.1 KB",
    isRaster: false,
  },
  {
    name: "Nbe",
    filename: "Nbe.tsx",
    type: "Raster Image",
    sizeBytes: 45555,
    sizeFormatted: "44.5 KB",
    isRaster: true,
  },
  {
    name: "NoahRealEstate",
    filename: "NoahRealEstate.tsx",
    type: "Raster Image",
    sizeBytes: 13857,
    sizeFormatted: "13.5 KB",
    isRaster: true,
  },
  {
    name: "Noc",
    filename: "Noc.tsx",
    type: "Raster Image",
    sizeBytes: 35103,
    sizeFormatted: "34.3 KB",
    isRaster: true,
  },
  {
    name: "NyalaMotors",
    filename: "NyalaMotors.tsx",
    type: "Raster Image",
    sizeBytes: 52319,
    sizeFormatted: "51.1 KB",
    isRaster: true,
  },
  {
    name: "OldEthio",
    filename: "OldEthio.tsx",
    type: "Pure Vector",
    sizeBytes: 16730,
    sizeFormatted: "16.3 KB",
    isRaster: false,
  },
  {
    name: "Opm",
    filename: "Opm.tsx",
    type: "Raster Image",
    sizeBytes: 161443,
    sizeFormatted: "157.7 KB",
    isRaster: true,
  },
  {
    name: "OromiaBank",
    filename: "OromiaBank.tsx",
    type: "Raster Image",
    sizeBytes: 128705,
    sizeFormatted: "125.7 KB",
    isRaster: true,
  },
  {
    name: "Qinash",
    filename: "Qinash.tsx",
    type: "Raster Image",
    sizeBytes: 27904,
    sizeFormatted: "27.3 KB",
    isRaster: true,
  },
  {
    name: "RadissonBlu",
    filename: "RadissonBlu.tsx",
    type: "Pure Vector",
    sizeBytes: 8525,
    sizeFormatted: "8.3 KB",
    isRaster: false,
  },
  {
    name: "Ramada",
    filename: "Ramada.tsx",
    type: "Raster Image",
    sizeBytes: 80868,
    sizeFormatted: "79.0 KB",
    isRaster: true,
  },
  {
    name: "Ride",
    filename: "Ride.tsx",
    type: "Raster Image",
    sizeBytes: 45731,
    sizeFormatted: "44.7 KB",
    isRaster: true,
  },
  {
    name: "Safaricom",
    filename: "Safaricom.tsx",
    type: "Pure Vector",
    sizeBytes: 3992,
    sizeFormatted: "3.9 KB",
    isRaster: false,
  },
  {
    name: "Sap",
    filename: "Sap.tsx",
    type: "Raster Image",
    sizeBytes: 26512,
    sizeFormatted: "25.9 KB",
    isRaster: true,
  },
  {
    name: "SaveTheChildren",
    filename: "SaveTheChildren.tsx",
    type: "Raster Image",
    sizeBytes: 92983,
    sizeFormatted: "90.8 KB",
    isRaster: true,
  },
  {
    name: "Sheraton",
    filename: "Sheraton.tsx",
    type: "Pure Vector",
    sizeBytes: 12274,
    sizeFormatted: "12.0 KB",
    isRaster: false,
  },
  {
    name: "SheratonResorts",
    filename: "SheratonResorts.tsx",
    type: "Pure Vector",
    sizeBytes: 16184,
    sizeFormatted: "15.8 KB",
    isRaster: false,
  },
  {
    name: "Sirabota",
    filename: "Sirabota.tsx",
    type: "Pure Vector",
    sizeBytes: 5234,
    sizeFormatted: "5.1 KB",
    isRaster: false,
  },
  {
    name: "SugarCorporation",
    filename: "SugarCorporation.tsx",
    type: "Raster Image",
    sizeBytes: 26517,
    sizeFormatted: "25.9 KB",
    isRaster: true,
  },
  {
    name: "Sunshine",
    filename: "Sunshine.tsx",
    type: "Raster Image",
    sizeBytes: 14307,
    sizeFormatted: "14.0 KB",
    isRaster: true,
  },
  {
    name: "Telebirr",
    filename: "Telebirr.tsx",
    type: "Pure Vector",
    sizeBytes: 2963,
    sizeFormatted: "2.9 KB",
    isRaster: false,
  },
  {
    name: "Tomoca",
    filename: "Tomoca.tsx",
    type: "Raster Image",
    sizeBytes: 83984,
    sizeFormatted: "82.0 KB",
    isRaster: true,
  },
  {
    name: "TourismEthiopia",
    filename: "TourismEthiopia.tsx",
    type: "Raster Image",
    sizeBytes: 98807,
    sizeFormatted: "96.5 KB",
    isRaster: true,
  },
  {
    name: "TsehayRealEstate",
    filename: "TsehayRealEstate.tsx",
    type: "Raster Image",
    sizeBytes: 32195,
    sizeFormatted: "31.4 KB",
    isRaster: true,
  },
  {
    name: "Uneca",
    filename: "Uneca.tsx",
    type: "Raster Image",
    sizeBytes: 8344,
    sizeFormatted: "8.1 KB",
    isRaster: true,
  },
  {
    name: "WashingtonMedical",
    filename: "WashingtonMedical.tsx",
    type: "Raster Image",
    sizeBytes: 24538,
    sizeFormatted: "24.0 KB",
    isRaster: true,
  },
  {
    name: "WegagenBank",
    filename: "WegagenBank.tsx",
    type: "Pure Vector",
    sizeBytes: 7886,
    sizeFormatted: "7.7 KB",
    isRaster: false,
  },
  {
    name: "YotekRealEstate",
    filename: "YotekRealEstate.tsx",
    type: "Raster Image",
    sizeBytes: 32647,
    sizeFormatted: "31.9 KB",
    isRaster: true,
  },
  {
    name: "ZemenBank",
    filename: "ZemenBank.tsx",
    type: "Pure Vector",
    sizeBytes: 7825,
    sizeFormatted: "7.6 KB",
    isRaster: false,
  },
  {
    name: "ZemenGebeya",
    filename: "ZemenGebeya.tsx",
    type: "Raster Image",
    sizeBytes: 30264,
    sizeFormatted: "29.6 KB",
    isRaster: true,
  },
];
